### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

### ISSUE THREAD

**Issue by chunLinssp** [wechaty/java-wechaty#106]
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.start(PuppetGrpc.java:2744)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:78)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)

docker端生成token，java端使用token；两者通信正常（ping的通，端口监听开放）
有没有解决的方案呢？

**Comment by zywaiting** [comment]
token 如何获得

**Comment by zhihuifanqiechaodan** [comment]
> 

找你使用的puppet服务的服务商购买，你可以参考文档说明：https://wechaty.js.org/docs/puppet-services/overview

**Comment by zywaiting** [comment]
UNAVAILABLE: Network closed for unknown reason
这个怎么解决

**Comment by zywaiting** [comment]
UNAVAILABLE: io exception

**Comment by csdwd** [comment]
我的办法是 用 wechaty：0.56版本

**Comment by felixu1992** [comment]
最后你怎么解决的啊

**Comment by duanxr** [comment]
https://github.com/wechaty/puppet-service/issues/160

This is worked for me, check it

**Comment by sfw0807** [comment]
> 最后你怎么解决的啊

这个问题解决了吗，我也卡在这了

**Comment by felixu1992** [comment]
> > 最后你怎么解决的啊
> 
> 这个问题解决了吗，我也卡在这了

降版本，这 *Java* 版本写的比较坑，还是用 *Python* 的吧
