### ISSUE TITLE
多二维码问题

### ISSUE THREAD

**Issue by suruozhong** [wechaty/java-wechaty#26]
1，登录情况下，我重启程序，没自动登录，会显示新的二维码，但微信上没退出登录还是显示windows在线。扫新的二维码显示二维码是过期的
2，我退出windows登录，多试几次，会出现多个二维码，扫码登录收不到消息了
3，修改群名称会报错
2020-06-02 15:57:14.782 ERROR 16040 --- [ool-15-thread-9] io.github.wechaty.grpc.GrpcPuppet        : error

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "timestamp" (class io.github.wechaty.schemas.EventRoomTopicPayload), not marked as ignorable (5 known properties: "oldTopic", "timstamp", "changerId", "roomId", "newTopic"])
 at [Source: (String)"{"changerId":"suruozhong","newTopic":"robot","oldTopic":"robot1","roomId":"23431178914@chatroom","timestamp":1591084633}"; line: 1, column: 121] (through reference chain: io.github.wechaty.schemas.EventRoomTopicPayload["timestamp"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3417)
	at io.github.wechaty.grpc.GrpcPuppet.onGrpcStreamEvent(GrpcPuppet.kt:1076)
	at io.github.wechaty.grpc.GrpcPuppet.access$onGrpcStreamEvent(GrpcPuppet.kt:28)
	at io.github.wechaty.grpc.GrpcPuppet$startGrpcStream$streamObserver$1.onNext(GrpcPuppet.kt:165)
	at io.github.wechaty.grpc.GrpcPuppet$startGrpcStream$streamObserver$1.onNext(GrpcPuppet.kt:163)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:434)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:599)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by diaozxin007** [comment]
问题  1，2，大概率是远程服务的问题，可以在群内反馈问题。
问题 3，近期修复 @redmaple1

**Comment by wj-Mcat** [comment]
@diaozxin007 I also meet this error. I thinks it's a bug of hostie server.  

`WatingForScan` status should be single during one request. But receive serval times from hostie-server.

**Comment by su-chang** [comment]
> 2，我退出windows登录，多试几次，会出现多个二维码，扫码登录收不到消息了

I will check and resolve it.

**Comment by redmaple1** [comment]
> 问题 3，近期修复 @redmaple1
I will check and resolve it.

**Comment by diaozxin007** [comment]
问题 3 已经修复

**Comment by suruozhong** [comment]
经多次验证，上述问题已完美解决，非常棒
