### ISSUE TITLE
How to get contactList

### ISSUE THREAD

**Issue by windiam** [wechaty/java-wechaty#37]
When I execute the method "wechaty().getContactManager().findAll(filter)", excepiton occurs.

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_77]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_77]
	at io.github.wechaty.user.manager.ContactManager.findAll(ContactManager.kt:49) ~[wechaty-0.1.3-SNAPSHOT.jar:?]
	at io.github.wechaty.example.Main.lambda$1(Main.java:24) ~[classes/:?]
	at io.github.wechaty.Wechaty$on$1.handler(Wechaty.kt:119) [wechaty-0.1.3-SNAPSHOT.jar:?]
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49) [wechaty-puppet-0.1.3-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.util.stream.AbstractPipeline.<init>(AbstractPipeline.java:203) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline.<init>(ReferencePipeline.java:94) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline$StatelessOp.<init>(ReferencePipeline.java:618) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline$3.<init>(ReferencePipeline.java:187) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline.map(ReferencePipeline.java:186) ~[?:1.8.0_77]
	at io.github.wechaty.Puppet$contactSearch$1.get(Puppet.kt:462) ~[wechaty-puppet-0.1.3-SNAPSHOT.jar:?]
	at io.github.wechaty.Puppet$contactSearch$1.get(Puppet.kt:37) ~[wechaty-puppet-0.1.3-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_77]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_77]

**Comment by diaozxin007** [comment]
it looks like a bug.will fix it next version

**Comment by diaozxin007** [comment]
fixed
