### ISSUE TITLE
puppet_padplus_3e5aXXXXXXX的token

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#46]
背景
1、linux的docker跑起来了
2、客户端jdk用了1.8 ，运行起来后，后台能够看到群讨论记录的打印
      类似：
      03:32:52 VERB IoClient onMessage(Message#Text[🗣Contact<hi多大>@👥Room<“XXXX讲潮牌”（一群）>]     @杭州•岳 ) 不能完全认可.
3、客户端采用的代码
     java-wechaty-getting-started

但是更多是如下错误
1、docker端

2020-07-03T03:29:44.761706176Z Error [AssertionError]: Assertion failed
2020-07-03T03:29:44.761714398Z     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
2020-07-03T03:29:44.761718004Z     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
2020-07-03T03:29:44.761721136Z     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
2020-07-03T03:29:44.761724220Z     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
2020-07-03T03:29:44.761727299Z     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
2020-07-03T03:29:44.761730162Z     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
2020-07-03T03:29:44.761733086Z     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
2020-07-03T03:29:44.761749627Z     at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
2020-07-03T03:29:44.761753025Z     at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
2020-07-03T03:29:44.761756063Z     at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
2020-07-03T03:29:44.761758865Z     at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
2020-07-03T03:29:44.761761665Z     at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
2020-07-03T03:29:44.761764667Z     at Generator.next (<anonymous>)
2020-07-03T03:29:44.761767398Z     at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
2020-07-03T03:29:44.761770241Z     at runMicrotasks (<anonymous>)
2020-07-03T03:29:44.761773036Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-07-03T03:29:44.761778143Z   reportErrorToServer: true,
2020-07-03T03:29:44.761780927Z   messagePattern: 'Assertion failed',
2020-07-03T03:29:44.761783601Z   code: 13
2020-07-03T03:29:44.761786296Z }
2020-07-03T03:29:44.761788788Z 03:29:44 VERB PuppetServiceImpl messagePayload()
2020-07-03T03:29:44.761791379Z 03:29:44 VERB Puppet messagePayload(2149790006771429387)
2020-07-03T03:29:44.761793995Z Error [AssertionError]: Assertion failed
2020-07-03T03:29:44.761796555Z     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
2020-07-03T03:29:44.761799358Z     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
2020-07-03T03:29:44.761802274Z     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
2020-07-03T03:29:44.761805249Z     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
2020-07-03T03:29:44.761808019Z     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
2020-07-03T03:29:44.761810816Z     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
2020-07-03T03:29:44.761813681Z     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
2020-07-03T03:29:44.761816893Z     at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
2020-07-03T03:29:44.761829647Z     at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
2020-07-03T03:29:44.761832852Z     at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
2020-07-03T03:29:44.761835836Z     at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
2020-07-03T03:29:44.761838544Z     at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
2020-07-03T03:29:44.761841438Z     at Generator.next (<anonymous>)
2020-07-03T03:29:44.761844142Z     at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
2020-07-03T03:29:44.761846934Z     at runMicrotasks (<anonymous>)
2020-07-03T03:29:44.761849620Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-07-03T03:29:44.761852421Z   reportErrorToServer: true,
2020-07-03T03:29:44.761855220Z   messagePattern: 'Assertion failed',
2020-07-03T03:29:44.761861105Z   code: 13
2020-07-03T03:29:44.761863731Z }
2020-07-03T03:29:44.770798332Z 03:29:44 VERB PuppetServiceImpl messagePayload()
2020-07-03T03:29:44.770831364Z 03:29:44 VERB Puppet messagePayload(8068032150445748047)
2020-07-03T03:29:44.771273379Z Error [AssertionError]: Assertion failed
2020-07-03T03:29:44.771283764Z     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
2020-07-03T03:29:44.771287812Z     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
2020-07-03T03:29:44.771290983Z     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
2020-07-03T03:29:44.771297830Z     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
2020-07-03T03:29:44.771301037Z     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
2020-07-03T03:29:44.771304006Z     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
2020-07-03T03:29:44.771306989Z     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
2020-07-03T03:29:44.771310210Z     at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
2020-07-03T03:29:44.771313120Z     at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
2020-07-03T03:29:44.771330478Z     at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
2020-07-03T03:29:44.771333707Z     at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
2020-07-03T03:29:44.771336483Z     at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
2020-07-03T03:29:44.771339511Z     at Generator.next (<anonymous>)
2020-07-03T03:29:44.771342236Z     at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
2020-07-03T03:29:44.771345086Z     at runMicrotasks (<anonymous>)
2020-07-03T03:29:44.771347809Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-07-03T03:29:44.771353495Z   reportErrorToServer: true,
2020-07-03T03:29:44.771358777Z   messagePattern: 'Assertion failed',
2020-07-03T03:29:44.771361534Z   code: 13
2020-07-03T03:29:44.771364276Z }
2020-07-03T03:29:44.775711043Z 03:29:44 VERB PuppetServiceImpl messagePayload()
2020-07-03T03:29:44.775732115Z 03:29:44 VERB Puppet messagePayload(2149790006771429387)
2020-07-03T03:29:44.775736224Z Error [AssertionError]: Assertion failed
2020-07-03T03:29:44.775739115Z     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
2020-07-03T03:29:44.775745666Z     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
2020-07-03T03:29:44.775748917Z     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
2020-07-03T03:29:44.775752062Z     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
2020-07-03T03:29:44.775755041Z     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
2020-07-03T03:29:44.775760502Z     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
2020-07-03T03:29:44.775763984Z     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
2020-07-03T03:29:44.775767139Z     at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
2020-07-03T03:29:44.775770099Z     at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
2020-07-03T03:29:44.775773311Z     at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
2020-07-03T03:29:44.775787817Z     at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
2020-07-03T03:29:44.775790881Z     at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
2020-07-03T03:29:44.775793877Z     at Generator.next (<anonymous>)
2020-07-03T03:29:44.775796659Z     at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
2020-07-03T03:29:44.775799528Z     at runMicrotasks (<anonymous>)
2020-07-03T03:29:44.775802263Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-07-03T03:29:44.775805046Z   reportErrorToServer: true,
2020-07-03T03:29:44.775807814Z   messagePattern: 'Assertion failed',
2020-07-03T03:29:44.775810645Z   code: 13
2020-07-03T03:29:44.775813387Z }
2020-07-03T03:29:44.775816505Z 03:29:44 VERB PuppetServiceImpl messagePayload()

2、 客户端如下
12:25:07.386 [pool-9-thread-3]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1593750307386
12:25:07.386 [pool-13-thread-5]DEBUG io.github.wechaty.grpc.GrpcPuppet-[946]  - PuppetHostie EVENT_TYPE_MESSAGE payload {"messageId":"5095696973674313635"}
12:25:07.387 [pool-9-thread-5]DEBUG io.github.wechaty.Puppet-[267]  - class Type is io.github.wechaty.schemas.EventHeartbeatPayload
12:25:07.387 [pool-9-thread-5]DEBUG io.github.wechaty.Puppet-[79]  - heartbeat -> heartbeat
12:25:07.387 [pool-9-thread-5]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[68]  - feed dog WatchdogFood(timeout=60000, data=heartbeat)
12:25:07.387 [pool-9-thread-5]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1593750307387
Exception in thread "pool-9-thread-2" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$7.handler(Wechaty.kt:260)
	at io.github.wechaty.Puppet$on$12.handler(Puppet.kt:257)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:183)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.Puppet$messagePayload$1$1.apply(Puppet.kt:625)
	at io.github.wechaty.Puppet$messagePayload$1$1.apply(Puppet.kt:37)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:238)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:234)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at io.github.wechaty.Puppet$messagePayload$1.get(Puppet.kt:624)
	at io.github.wechaty.Puppet$messagePayload$1.get(Puppet.kt:37)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	... 9 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.messagePayload(PuppetGrpc.java:2891)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:657)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:29)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	... 25 more
Exception in thread "pool-9-thread-10" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$7.handler(Wechaty.kt:260)
	at io.github.wechaty.Puppet$on$12.handler(Puppet.kt:257)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Assertion failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:183)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by redmaple1** [comment]
Thanks for your issue.   
Please use a donut token.Not a padplus token.  
You can add @Juzi BOT as wechat friend.And apply a donut token to use.

**Comment by jcai** [comment]
@landgreenland you can try 

```
docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
 docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
```

**Comment by landgreenland** [comment]
> @landgreenland you can try
> 
> ```
> docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
>  docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
> ```

  zixia/wechaty修改为 docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
是这个意思么 ？

**Comment by landgreenland** [comment]
> Thanks for your issue.
> Please use a donut token.Not a padplus token.
> You can add @juzi BOT as wechat friend.And apply a donut token to use.

你好，啥意思 能联系我qq么2500089611

**Comment by redmaple1** [comment]
> > Thanks for your issue.
> > Please use a donut token.Not a padplus token.
> > You can add @juzi BOT as wechat friend.And apply a donut token to use.
> 
> 你好，啥意思 能联系我qq么2500089611

Now can only use padplus token on docker.But need to run a token gateway to transform.Please see:[https://github.com/wechaty/wechaty/issues/1985](https://github.com/wechaty/wechaty/issues/1985)  

If you want to get a donut token,please contact Juzi BOT. We just talked about your conversation on wechat.Juzi BOT will handle it later.

**Comment by landgreenland** [comment]
> > > Thanks for your issue.
> > > Please use a donut token.Not a padplus token.
> > > You can add @juzi BOT as wechat friend.And apply a donut token to use.
> > 
> > 
> > 你好，啥意思 能联系我qq么2500089611
> 
> Now can only use padplus token on docker.But need to run a token gateway to transform.Please see:[wechaty/wechaty#1985](https://github.com/wechaty/wechaty/issues/1985)
> 
> If you want to get a donut token,please contact Juzi BOT. We just talked about your conversation on wechat.Juzi BOT will handle it later.

doker的gateway都搞定了 ，也跑起来了。
然后就在本地跑这个客户端程序（具体issue中都有描述）


其他方式暂时不考虑

就是不行
官方说padplus token稳定的。

那么问题到底在哪里

**Comment by huan** [comment]
This bug should be fixed by https://github.com/wechaty/wechaty-puppet-padplus/pull/273

Link to https://github.com/wechaty/wechaty/issues/1985
