### ISSUE TITLE
几个常见问题

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#49]
问题1
02:01:21 ERR Config ###########################
02:01:21 ERR Config unhandledRejection: Error: get contact timeout
    at Timeout._onTimeout (/wechaty/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:1169:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) [object Promise]
02:01:21 ERR Config ###########################
02:01:21 ERR Config process.on(unhandledRejection) promise.catch(get contact timeout)
Config Error: get contact timeout
    at Timeout._onTimeout (/wechaty/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:1169:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:40) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 407)

导致message事件捕捉不到。

**Comment by landgreenland** [comment]
问题2

02:03:05 ERR GRPC_GATEWAY ApiType: SEND_MESSAGE request timeout, traceId: 13ad6b96-963d-40a9-bb6f-dd1486cf5e47
02:03:05 ERR PuppetServiceImpl grpcError() messageSendContact() rejection: can not send message due to this error: Error: can not get response from grpc server
{
  code: 13,
  details: 'can not send message due to this error: Error: can not get response from grpc server'
}
02:03:06 VERB PuppetServiceImpl ding()
02:03:06 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"`recover CPR #14"})
02:03:06 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"`recover CPR #14"})
02:03:10 ERR GRPC_GATEWAY ApiType: SEND_MESSAGE request timeout, traceId: cde19a3a-3a33-41bc-af85-5db061d8b2e6
02:03:10 ERR PuppetServiceImpl grpcError() messageSendContact() rejection: can not send message due to this error: Error: can not get response from grpc server
{
  code: 13,
  details: 'can not send message due to this error: Error: can not get response from grpc server'
}
02:03:10 ERR GRPC_GATEWAY ApiType: SEND_MESSAGE request timeout, traceId: 94044676-b288-4b4a-8cc3-692125c91f61
02:03:10 ERR PuppetServiceImpl grpcError() messageSendContact() rejection: can not send message due to this error: Error: can not get response from grpc server
{
  code: 13,
  details: 'can not send message due to this error: Error: can not get response from grpc server'
}
02:03:10 ERR GRPC_GATEWAY ApiType: SEND_MESSAGE request timeout, traceId: cb14c202-534c-4aab-b086-f863dfe1fde7
02:03:10 ERR PuppetServiceImpl grpcError() messageSendContact() rejection: can not send message due to this error: Error: can not get response from grpc server
{
  code: 13,
  details: 'can not send message due to this error: Error: can not get response from grpc server'
}
