### ISSUE TITLE
SDK的message的type的bug

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#54]
转发一个网页 得到的类型是Video  
不是应该为url么

        <wechaty.version>0.1.4-SNAPSHOT</wechaty.version>

**Comment by landgreenland** [comment]
群里发一个视频得到错误如下
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at io.github.wechaty.grpc.puppet.Message$MessageType.getNumber(Message.java:149)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:665)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:29)
	... 8 more
Exception in thread "pool-8-thread-10" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$7.handler(Wechaty.kt:260)
	at io.github.wechaty.Puppet$on$12.handler(Puppet.kt:257)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:183)
	at io.github.wechaty.user.Message$ready$1.get(Message.kt:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.github.wechaty.Puppet$messagePayload$1$1.apply(Puppet.kt:625)
	at io.github.wechaty.Puppet$messagePayload$1$1.apply(Puppet.kt:37)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:238)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:234)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at io.github.wechaty.Puppet$messagePayload$1.get(Puppet.kt:624)
	at io.github.wechaty.Puppet$messagePayload$1.get(Puppet.kt:37)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at io.github.wechaty.grpc.puppet.Message$MessageType.getNumber(Message.java:149)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:665)
	at io.github.wechaty.grpc.GrpcPuppet$messageRawPayload$1.get(GrpcPuppet.kt:29)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	... 27 more

**Comment by landgreenland** [comment]
收到红包的type为Recalled，是不是应该为RedEnvelope？  RedEnvelope是什么场景下触发呢
