### ISSUE TITLE
升级版本后启动报错

### ISSUE THREAD

**Issue by windiam** [wechaty/java-wechaty#58]
Caused by: java.lang.RuntimeException: expect one puppet,but can not found any one.
	at io.github.wechaty.user.manager.PuppetManager$Companion.resolveInstance(PuppetManager.kt:29) ~[wechaty-0.1.4-SNAPSHOT.jar:?]
	at io.github.wechaty.Wechaty.initPuppet(Wechaty.kt:176) ~[wechaty-0.1.4-SNAPSHOT.jar:?]
	at io.github.wechaty.Wechaty.start(Wechaty.kt:51) ~[wechaty-0.1.4-SNAPSHOT.jar:?]

**Comment by redmaple1** [comment]
In 0.1.4-SNAPSHOT version, we use puppetManager to manage puppet implementations and removed puppet implementations from wechaty pom. Which implementation to use depends on which implementation jar in your pom. You need to depend puppet hostie on your pom now.  Like this:  
```java
<dependency>
      <groupId>io.github.wechaty</groupId>
      <artifactId>wechaty-puppet-hostie</artifactId>
      <version>0.1.4-SNAPSHOT</version>
 </dependency>
```  
You can see: [https://github.com/wechaty/java-wechaty-getting-started](https://github.com/wechaty/java-wechaty-getting-started).    

Maybe in next version, we'll improve this to depend a default puppet implementation, then users can not need to depend puppet-hostie themselves.
