### ISSUE TITLE
JAVA SDK异常  客户端作业的时候报错如下

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#61]
2020-07-13 15:06:21.352 ERROR io.github.wechaty.grpc.GrpcPuppet - error
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "timeout" (class io.github.wechaty.schemas.EventHeartbeatPayload), not marked as ignorable (one known property: "data"])
 at [Source: (String)"{"data":"2f2b1191-4dc5-4813-b4de-8c57b1bcbae8","timeout":60000}"; line: 1, column: 63] (through reference chain: io.github.wechaty.schemas.EventHeartbeatPayload["timeout"])
 at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
 at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
 at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:263)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3417)
 at io.github.wechaty.grpc.GrpcPuppet.onGrpcStreamEvent(GrpcPuppet.kt:1051)
 at io.github.wechaty.grpc.GrpcPuppet.access$onGrpcStreamEvent(GrpcPuppet.kt:29)
 at io.github.wechaty.grpc.GrpcPuppet$startGrpcStr

**Comment by diaozxin007** [comment]
fixed
