### ISSUE TITLE
关于java版本的sdk稳定性的疑问（docker？sdk?）

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#69]
非常奇怪的问题
https://api.chatie.io/v0/hosties/puppet_padplus_1663d4xxxx
正常返回IP  
docker成功启动，且docker日志都能捕捉到群消息
但是用java的demo程序，
扫码登录后，onmessage正常执行一段时间后（2~3个小时），
就不能捕捉到onmessage事件。

**Comment by landgreenland** [comment]
2020-07-27 11:26:28.591 WARN  io.github.wechaty.grpc.GrpcPuppet - grpc client exit
七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=41, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=29, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=33, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=61, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=25, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=57, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=69, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=85, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=77, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

七月 27, 2020 11:26:33 上午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=45, target=120.92.217.80:8788} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:158)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:74)
	at io.github.wechaty.Puppet.reset(Puppet.kt:310)
	at io.github.wechaty.Puppet$3.handler(Puppet.kt:104)
	at io.github.wechaty.Puppet$on$14.handler(Puppet.kt:278)
	at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by landgreenland** [comment]
以上问题  docker端都正常
如下

:27:58 VERB Message ready()
03:27:58 VERB Puppet messagePayload(8230426376955388248)
03:27:58 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"8230426376955388248"})
03:27:58 VERB Room ready()
03:27:58 VERB IoClient onMessage(Message#Emoticon[Contact<狼头领>@Room<乌鸦云计算-WuxinHub-体验客户>])
03:28:08 VERB Message static load(4143456328428124139)
03:28:08 VERB Message constructor(4143456328428124139) for class Message
03:28:08 VERB Message ready()
03:28:08 VERB Puppet messagePayload(4143456328428124139)
03:28:08 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"4143456328428124139"})
03:28:08 VERB Room ready()
03:28:08 VERB IoClient onMessage(Message#Text[Contact<.>@Room<烟雨江南-交友婚嫁板块>]	关窗没这习惯)
03:28:08 VERB Message static load(2740867116748392157)
03:28:08 VERB Message constructor(2740867116748392157) for class Message
03:28:08 VERB Message ready()
03:28:08 VERB Puppet messagePayload(2740867116748392157)
03:28:08 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"2740867116748392157"})
03:28:08 VERB Room ready()
03:28:08 VERB IoClient onMessage(Message#Text[Contact<ʜєʟʟɵ!!>@Room<烟雨江南-交友婚嫁板块>]	出门关窗)
03:28:31 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"","timeout":60000})
03:28:31 VERB Message static load(6102882370817257871)
03:28:31 VERB Message constructor(6102882370817257871) for class Message
03:28:31 VERB Message ready()
03:28:31 VERB Puppet messagePayload(6102882370817257871)
03:28:31 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"6102882370817257871"})
03:28:31 VERB Room ready()
03:28:31 VERB IoClient onMessage(Message#Text[Contact<.>@Room<烟雨江南-交友婚嫁板块>]	出门家里也不关窗[捂脸])
03:28:32 VERB Message static load(7669593420463939004)
03:28:32 VERB Message constructor(7669593420463939004) for class Message
03:28:32 VERB Message ready()
03:28:32 VERB Puppet messagePayload(7669593420463939004)
03:28:32 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"7669593420463939004"})
03:28:32 VERB Room ready()
03:28:32 VERB IoClient onMessage(Message#Text[Contact<风之子>@Room<烟雨江南-交友婚嫁板块>]	@喵87 那个滴水)

**Comment by zywaiting** [comment]
解决了吗
