### ISSUE TITLE
[Bug]use correct wxwork token，start wechaty,  get exception WriteBufferingAndExceptionHandler

### ISSUE THREAD

**Issue by freecto** [wechaty/java-wechaty#80]
do the following and get a exception:
1. clone code from git https://github.com/wechaty/java-wechaty
2. change the Wechaty token in file io.github.wechaty.example.Main.java
3. run the command:
mvn clean install
java -jar target/wechaty-example-1.0.0-SNAPSHOT-jar-with-dependencies.jar
4. get the exception:
[main] INFO org.reflections.Reflections - Reflections took 4016 ms to scan 1 urls, producing 3850 keys and 22251 values 
[main] ERROR io.github.wechaty.grpc.GrpcPuppet - start() rejection:
io.grpc.StatusRuntimeException: INTERNAL: channelRead() missed by ProtocolNegotiator handler: PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 1024)
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
        at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.start(PuppetGrpc.java:2744)
        at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:78)
        at io.github.wechaty.Wechaty.start(Wechaty.kt:52)
        at io.github.wechaty.example.Main.main(Main.java:29)
[main] INFO io.github.wechaty.Wechaty - start Wechaty
^C[StartMain-shutdown-hook] WARN io.github.wechaty.grpc.GrpcPuppet - stop() is called on a OFF puppet. await ready(off) and return.

**Comment by freecto** [comment]
got another issue:

[pool-9-thread-3] ERROR io.github.wechaty.user.Contact - ready() contactPayload 1688850734702140 error 
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.github.wechaty.Puppet.contactPayload(Puppet.kt:517)
        at io.github.wechaty.user.Contact.ready(Contact.kt:84)
        at io.github.wechaty.user.Contact.ready$default(Contact.kt:76)
        at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$5.handler(Wechaty.kt:260)
        at io.github.wechaty.Puppet$on$10.handler(Puppet.kt:241)
        at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at io.github.wechaty.grpc.puppet.Contact$ContactType.getNumber(Contact.java:170)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:410)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:29)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Exception in thread "pool-9-thread-3" java.lang.Error: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.github.wechaty.Puppet.contactPayload(Puppet.kt:517)
        at io.github.wechaty.user.Contact.ready(Contact.kt:84)
        at io.github.wechaty.user.Contact.ready$default(Contact.kt:76)
        at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$5.handler(Wechaty.kt:260)
        at io.github.wechaty.Puppet$on$10.handler(Puppet.kt:241)
        at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at io.github.wechaty.grpc.puppet.Contact$ContactType.getNumber(Contact.java:170)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:410)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:29)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
