### ISSUE TITLE
 [question] this eventName:START has no listener      

### ISSUE THREAD

**Issue by wxnyzl** [wechaty/java-wechaty#81]
昨日还好好地,早上来就是这样,接收不到信息,也不能发送
17:08:12.929 [main]INFO  org.reflections.Reflections-[229]  - Reflections took 102 ms to scan 4 urls, producing 159 keys and 1545 values 
17:08:14.622 [main]DEBUG io.github.wechaty.grpc.GrpcPuppet-[76]  - IDLE
17:08:14.964 [main]DEBUG io.github.wechaty.eventEmitter.EventEmitter-[43]  - **this eventName:START has no listener**
17:08:14.964 [main]INFO  io.github.wechaty.Wechaty-[58]  - start Wechaty
17:08:15.003 [pool-14-thread-1]DEBUG io.github.wechaty.grpc.GrpcPuppet-[946]  - PuppetHostie EVENT_TYPE_LOGIN payload {"contactId":"wxid_bil9bkbyn47522"}
17:08:15.005 [pool-10-thread-1]DEBUG io.github.wechaty.Puppet-[267]  - class Type is io.github.wechaty.schemas.EventHeartbeatPayload
17:08:15.005 [pool-10-thread-1]DEBUG io.github.wechaty.Puppet-[79]  - heartbeat -> heartbeat
17:08:15.006 [pool-10-thread-1]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[68]  - feed dog WatchdogFood(timeout=60000, data=heartbeat)
17:08:15.006 [pool-10-thread-1]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1605258495006
17:08:15.040 [pool-10-thread-2]DEBUG io.github.wechaty.Puppet-[501]  - contactPayload is null by id wxid_bil9bkbyn47522
17:08:27.946 [pool-11-thread-1]DEBUG io.github.wechaty.Puppet-[133]  - HEARTBEAT_COUNTER #1
17:08:27.979 [pool-14-thread-2]DEBUG io.github.wechaty.grpc.GrpcPuppet-[946]  - PuppetHostie EVENT_TYPE_DONG payload {"data":"`recover CPR #1"}
17:08:27.979 [pool-10-thread-3]DEBUG io.github.wechaty.Puppet-[267]  - class Type is io.github.wechaty.schemas.EventHeartbeatPayload
17:08:27.979 [pool-10-thread-3]DEBUG io.github.wechaty.Puppet-[79]  - heartbeat -> heartbeat
17:08:27.979 [pool-10-thread-3]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[68]  - feed dog WatchdogFood(timeout=60000, data=heartbeat)
17:08:27.979 [pool-10-thread-3]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1605258507979
17:08:27.983 [pool-10-thread-4]DEBUG io.github.wechaty.Puppet-[158]  - class Type is io.github.wechaty.schemas.EventDongPayload
17:08:27.983 [pool-10-thread-4]DEBUG io.github.wechaty.eventEmitter.EventEmitter-[43]  - **this eventName:DONG has no listener**
17:08:42.945 [pool-11-thread-1]DEBUG io.github.wechaty.Puppet-[133]  - HEARTBEAT_COUNTER #2
17:08:42.974 [pool-14-thread-3]DEBUG io.github.wechaty.grpc.GrpcPuppet-[946]  - PuppetHostie EVENT_TYPE_DONG payload {"data":"`recover CPR #2"}
17:08:42.975 [pool-10-thread-5]DEBUG io.github.wechaty.Puppet-[267]  - class Type is io.github.wechaty.schemas.EventHeartbeatPayload
17:08:42.975 [pool-10-thread-5]DEBUG io.github.wechaty.Puppet-[79]  - heartbeat -> heartbeat
17:08:42.975 [pool-10-thread-5]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[68]  - feed dog WatchdogFood(timeout=60000, data=heartbeat)
17:08:42.975 [pool-10-thread-6]DEBUG io.github.wechaty.Puppet-[158]  - class Type is io.github.wechaty.schemas.EventDongPayload
17:08:42.975 [pool-10-thread-5]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1605258522975
17:08:42.975 [pool-10-thread-6]DEBUG io.github.wechaty.eventEmitter.EventEmitter-[43]  - **this eventName:DONG has no listener**
17:08:57.946 [pool-11-thread-1]DEBUG io.github.wechaty.Puppet-[133]  - HEARTBEAT_COUNTER #3
17:08:57.975 [pool-14-thread-4]DEBUG io.github.wechaty.grpc.GrpcPuppet-[946]  - PuppetHostie EVENT_TYPE_DONG payload {"data":"`recover CPR #3"}
17:08:57.975 [pool-10-thread-7]DEBUG io.github.wechaty.Puppet-[267]  - class Type is io.github.wechaty.schemas.EventHeartbeatPayload
17:08:57.975 [pool-10-thread-7]DEBUG io.github.wechaty.Puppet-[79]  - heartbeat -> heartbeat
17:08:57.975 [pool-10-thread-7]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[68]  - feed dog WatchdogFood(timeout=60000, data=heartbeat)
17:08:57.975 [pool-10-thread-8]DEBUG io.github.wechaty.Puppet-[158]  - class Type is io.github.wechaty.schemas.EventDongPayload
17:08:57.975 [pool-10-thread-7]DEBUG io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[79]  - lastFeed is 1605258537975
17:08:57.975 [pool-10-thread-8]DEBUG io.github.wechaty.eventEmitter.EventEmitter-[43]  - **this eventName:DONG has no listener**

**Comment by wxnyzl** [comment]
token 版本  puppet_donut_xxx

**Comment by wxnyzl** [comment]
Exception in thread "Timer-0" java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: can not get message callback response, data: {"content":"现在是11点48分","to_wxid":"wxid_mq9g2u2w3w7822"}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
	at io.github.wechaty.user.Contact.say(Contact.kt:42)
	at com.sq.game.config.JobSend.sendMsg(JobSend.java:44)
	at com.sq.game.config.JobSend$ITask.run(JobSend.java:78)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: can not get message callback response, data: {"content":"现在是11点48分,","to_wxid":"wxid_mq9g2u2w3w7822"}
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.messageSendText(PuppetGrpc.java:2947)
	at io.github.wechaty.grpc.GrpcPuppet$messageSendText$1.get(GrpcPuppet.kt:620)
	at io.github.wechaty.grpc.GrpcPuppet$messageSendText$1.get(GrpcPuppet.kt:29)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by wxnyzl** [comment]
代码如下:接收不到消息
![image](https://user-images.githubusercontent.com/39220079/99494735-8062bb80-29ac-11eb-985e-53d01c0def38.png)

**Comment by diaozxin007** [comment]
大概率是 服务端的问题
