### ISSUE TITLE
直接运行examples出现错误 Can't get the number of an unknown enum value.

### ISSUE THREAD

**Issue by xy9860** [wechaty/java-wechaty#87]
0.`git clone https://github.com/wechaty/java-wechaty.git`
1.修改了文件加入了token(企业微信的token)
2.`cd examples/ &&  mvn install`
3.`java -jar target/wechaty-example-1.0.0-SNAPSHOT-jar-with-dependencies.jar`
4.
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "pool-9-thread-2" java.lang.Error: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.github.wechaty.Puppet.contactPayload(Puppet.kt:517)
        at io.github.wechaty.user.Contact.ready(Contact.kt:84)
        at io.github.wechaty.user.Contact.ready$default(Contact.kt:76)
        at io.github.wechaty.Wechaty$initPuppetEventBridge$$inlined$forEach$lambda$5.handler(Wechaty.kt:260)
        at io.github.wechaty.Puppet$on$10.handler(Puppet.kt:241)
        at io.github.wechaty.eventEmitter.EventEmitter$emit$$inlined$forEach$lambda$1.run(EventEmitter.kt:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
        at io.github.wechaty.grpc.puppet.Contact$ContactType.getNumber(Contact.java:170)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:410)
        at io.github.wechaty.grpc.GrpcPuppet$contactRawPayload$1.get(GrpcPuppet.kt:29)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

![1608968139(1)](https://user-images.githubusercontent.com/25838633/103147441-18b04500-4790-11eb-9af2-3e740f32bff6.jpg)

**Comment by HarrisonQi** [comment]
+1

**Comment by WuJingJava** [comment]
有解决？我现在也是这个问题

**Comment by shikouchen** [comment]
+1 有什么update吗

**Comment by aladinw** [comment]
+1

**Comment by aladinw** [comment]
这个问题你们有人解决了吗？
